version: '3.3'

services:
  ads:
    image: 'ads:latest'
    ports:
      - '8080:8080'
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
  adsfe:
    image: 'adsfe:lastest'
    ports:
      - '4200:4200'
    links:
      - 'ads'
    depends_on:
      - 'ads'

    networks:
      - backend

# Volumes
volumes:
  db:

# Networks to be created to facilitate communication between containers
networks:
  backend:
