version: '3.3'

services:
  localhost:
    image: 'ads:latest'
    ports:
      - '8080:8080'
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend1
  adsfe:
    image: 'adsfe:latest'
    ports:
      - '4200:80'
    depends_on:
      - 'localhost'
    networks:
      - backend1

# Networks to be created to facilitate communication between containers
networks:
  backend1:
