version: '3.3'

services:
  adsbe:
    image: 'jmam93/ads-be:latest'
    container_name: 'adsbe'
    ports:
      - '8080:8080'
    networks:
      - app-network
  adsfe:
    image: 'jmam93/ads-fe:latest'
    container_name: 'adsfe'
    ports:
      - '80:80'
    depends_on:
      - adsbe
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
