version: '3.3'

services:
  ads:
    image: 'ads:latest'
    ports:
      - '8080:8080'
  adsfe:
    image: 'adsfe:latest'
    ports:
      - '4200:80'
    links:
      - 'ads'
    depends_on:
      - 'ads'
